---
- name: Bastion networking playbook 
  hosts: bastion 
  become: True
  vars_files:
    - vars/vars.yaml
    - vars/services.yaml
  tasks:

    - name: Activating firewalld
      service:
        name: firewalld
        state: started
        enabled: true


    - name: "Getting {{ inventory_hostname }} ip address on first interface"
      set_fact:
        first_interface_ip: "{{ lookup('dig', ansible_host) }}"

    - name: Getting interface name connected to {{ first_interface_ip }}
      set_fact:
        first_interface: "{{ item }}"
      when:
        - hostvars[inventory_hostname]['ansible_{{ item }}']['ipv4'] is defined 
        - hostvars[inventory_hostname]['ansible_{{ item }}']['ipv4']['address'] == first_interface_ip
      with_items:
        - "{{ ansible_interfaces }}"

    - name: Getting second interface name
      set_fact:
        second_interface: "{{ item }}"
      when: 
        - item !='lo'
        - item != first_interface
      with_items:
        - "{{ ansible_interfaces }}"

    - name: Print detected interfaces name for {{ inventory_hostname }}
      debug:
        msg: >
             External interface: '{{ first_interface }}', 
             internal interface: '{{ second_interface }}'

    - name: Detect if {{ inventory_hostname }} can reach internet through first interface
      command: ping -c3 -I {{ first_interface }} 8.8.8.8
      changed_when: False

    - name: Detect if {{ inventory_hostname }} can resolve internet dns through first interface
      command: dig google.com
      changed_when: False
