---
- name: Preparing for disconnected OCP installation
  hosts: bastion
  gather_facts: false 
  become: true
  vars_files:
     - vars/vars.yaml
     - vars/downloads.yaml
     - vars/self_signed_certs.yaml
   
  tasks:
    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - podman
        - httpd-tools
        - python-pip

    - name: Installing pyopenssl
      command: pip install pyopenssl

    
    - name: Refreshing certificates dir
      file:
        path: "{{ cert_dir }}"
        state: absent
    
    - file:
        path: "{{ cert_dir }}"
        state: directory

    - name: "Generate the private key file to sign the CSR"
      openssl_privatekey:
        path: "{{ pempath }}"
        force: true

    - name: "Generate the CSR file signed with the private key"
      openssl_csr:
        path: "{{ csrpath }}"
        privatekey_path: "{{ pempath }}"
        common_name: "{{ dnsname }}"
        country_name: IT
        organization_name: ValeUbe
        subject_alt_name: 'DNS:{{ dnsname }}'

    - name: "Sign the CSR file as a CA to turn it into a certificate"
      openssl_certificate:
        path: "{{ crtpath }}"
        privatekey_path: "{{ pempath }}"
        csr_path: "{{ csrpath }}"
        provider: selfsigned

   
    
        
          
      