---
- name: Load balancer packages
  hosts: lb 
  become: True
  tasks:
     
    - name: Installing required packages
      package:
        name:
          - haproxy
        state: present

    - name: Installing semanage (Centos 8 minimal)
      package:
        name:
          - policycoreutils-python-utils
        state: present
      when: ansible_distribution == "CentOS" 
    