---
- hosts: localhost
  gather_facts: no
  tasks:
  - uri:
      url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/
      return_content: yes
    register: client_files
  
  - debug: var=oc_cli[0]
    vars:
      oc_cli: >
       {{ client_files.content | regex_findall('<a href=\"(.*)\">(.*)client-linux.tar.gz</a>')  }}