workspace_directory:
  base_path: /home/vale/ocpInstallerFile
  config_dir: config
  

networking:
  internal_network: 172.22.0.0
  internal_network_ip: 172.22.0.101
  internal_network_netmask: 255.255.255.0
  external_dns: 8.8.8.8
  domain_name: example.net

dhcp:
  timezone: "Europe/Rome"
  start: 172.22.0.201
  end: 172.22.0.250
  ntp: 204.11.201.10

lb:
 lb_internal_network_ip: 172.22.0.102
 internal_interface_mac: "56:6f:3d:48:00:03"
 name: lb

cluster:
  name: ocp
  ocp_user: vale
  ocp_pass: toor
  bootstrap:
      - mac: "56:6f:3d:48:00:0e"
  masters:
      - mac: "56:6f:3d:48:00:08"
      - mac: "56:6f:3d:48:00:09"
      - mac: "56:6f:3d:48:00:0a"
  workers:
      - mac: "56:6f:3d:48:00:0b"
      - mac: "56:6f:3d:48:00:0c"
      - mac: "56:6f:3d:48:00:0d"
      - mac: "56:6f:3d:48:00:11"
      - mac: "56:6f:3d:48:00:17"
      - mac: "56:6f:3d:48:00:18"
      - mac: "56:6f:3d:48:00:19"

  pullSecret: ''