---
- name: Variables checker
  hosts: localhost
  gather_facts: False
  vars_files: 
    - vars/vars.yaml
    - vars/downloads.yaml
    - vars/lb_firewall.yaml
  tasks:
    - name: Check for pullSecret variable
      debug:
        msg: "Check the pullSecret var in files/vars.yaml"
      failed_when: item
      loop:
        - "{{ (cluster.pullSecret is undefined) }}"
        - "{{ (cluster.pullSecret | length < 1) }}"
