---
- name: Ovirt provisioning
  hosts: ovirt_engine 
  become: True
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: https://{{ inventory_hostname }}/ovirt-engine/api
        username: "{{ ovirt.username }}"
        ca_file: "{{ ovirt.ca_file }}"
        password: "{{ ovirt.password }}"

    - name: Creating logical network
      ovirt_network:
        data_center: "{{ ovirt.data_center }}"
        clusters: 
          - name: "{{ ovirt.cluster }}"
            assigned: true
            required: false
            display: false
            migration: false
            gluster: false
        name: "{{ ovirt.network.internal.network }}"
        vm_network: true
        auth: "{{ ovirt_auth }}"
        state: present
        vlan_tag: 1

    - name: Assigning logical network to host network
      ovirt_host_network:
        auth: "{{ ovirt_auth }}"
        name: "{{ ovirt.host }}"
        interface: "{{ ovirt.network.internal.host_interface }}" 
        state: present
        networks:
          - name: "{{ ovirt.network.internal.network }}" 
            
        
    - name: Always revoke the SSO token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
 

