---
- name: Ovirt provisioning
  hosts: localhost 
  become: True
  gather_facts: false

  vars:
    engine_fqdn: ovengine.righini.local
    engine_user: vuberti@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    engine_password: vivaOpenshift

    debug_vm_create: yes
    db_vm:
      state: running
      cluster: Default
      #template: centos7
      memory: 2GiB
      #memory_max: 2GiB
      memory_guaranteed: 2Gib
      cores: 1
      tag:
        - db
        - dbvm
      disks:
        - size: 1GiB
          name: data
          storage_domain: hosted_storage
          interface: virtio

    vms:
      - name: aritest
        memory: 2GiB
        cloud_init:
          root_password: 'toor'
          authorized_ssh_keys: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
          regenerate_ssh_keys: yes
          host_name: test2.example.com
          dns_servers: 192.168.1.77
          nic_on_boot: true

        cloud_init_nics:
        - nic_name: eth0
          nic_boot_protocol: static
          nic_ip_address: 192.168.1.201
          nic_netmask: 255.255.255.0
          nic_gateway: 192.168.1.1
          nic_on_boot: true
          
        - nic_name: eth1
          nic_boot_protocol: none
          nic_on_boot: false

        nics:
          - name: eth0
            interface: virtio
            profile_name: ovirtmgmt/ovirtmgmt

          - name: eth1
            interface: virtio
            profile_name: openshift_net/openshift_net



        profile: "{{ db_vm }}"
        tag:
          - pgsql
          - httpd

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        hostname: "{{ engine_fqdn }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  roles:
    - ovirt.vm-infra

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
  
