---
- name: Ovirt provisioning
  hosts: localhost
  become: True
  gather_facts: false

  vars:
    engine_fqdn: ovengine.righini.local
    engine_user: vuberti@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    engine_password: vivaOpenshift

    qcow_url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2
    template_cluster: Default
    template_name: centos8_template_test
    template_memory: 4GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: big
    template_disk_bootable: true
    template_nics: []
    template_seal: false

    debug_vm_create: yes
    non_ocp_vm:
      state: running
      cluster: Default
      template: centos8_template_test
      memory: 2GiB
      memory_guaranteed: 2Gib
      nics:
          - name: eth0
            interface: virtio
            profile: vlan19
            network: vlan19

          - name: eth1
            interface: virtio
            profile: vlan22
            network: vlan22

    vms:
      - name: bastion_test
        cloud_init:
          root_password: 'toor'
          authorized_ssh_keys: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
          regenerate_ssh_keys: yes
          host_name: bastion_test.{{ networking.domain_name }}
          dns_servers: "{{ networking.external_dns }}"

        cloud_init_nics:
        - nic_name: eth0
          nic_boot_protocol: static
          nic_ip_address: 172.19.0.191
          nic_netmask: 255.255.255.0
          nic_gateway: 172.19.0.1
          nic_on_boot: true

        - nic_name: eth1
          nic_ip_address: "{{ networking.internal_network_ip }}"
          nic_netmask: "{{ networking.internal_network_netmask }}"
          #nic_gateway: 172.19.0.1
          nic_on_boot: false

        profile: "{{ non_ocp_vm }}"

      - name: lb_test
        cloud_init:
          root_password: 'toor'
          authorized_ssh_keys: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
          regenerate_ssh_keys: yes
          host_name: lb_test.{{ networking.domain_name }}
          dns_servers: "{{ networking.external_dns }}"

        cloud_init_nics:
        - nic_name: eth0
          nic_boot_protocol: static
          nic_ip_address: 172.19.0.192
          nic_netmask: 255.255.255.0
          nic_gateway: 172.19.0.1
          nic_on_boot: true

        - nic_name: eth1
          nic_ip_address: "{{ lb.lb_internal_network_ip }}"
          nic_netmask: "{{ {{ networking.internal_network_netmask }}"
          nic_on_boot: true

        profile: "{{ non_ocp_vm }}"
       
  roles:
    - ovirt.image-template
    - ovirt.vm-infra

