---
- name: Creating a workspace on Bastion
  hosts: bastion 
  gather_facts: no
  tasks:

    - name: Fetching release name
      uri:
        url: "{{ downloads.boot.base_url }}/sha256sum.txt"
        return_content: yes
      register: ocp_version

    - set_fact:
        installer_initramfs: '{{ ocp_version.content | regex_search("rhcos(.*)installer-initramfs(.*)") }}'

    - set_fact:
        installer_kernel: '{{ ocp_version.content | regex_search("rhcos(.*)installer-kernel(.*)") }}'

    - set_fact:
        coreos: '{{ ocp_version.content | regex_search("rhcos(.*)metal(.*)") }}'
   
    
    - name: Erasing dnsmasq lease
      file:
        path: /var/lib/dnsmasq/dnsmasq.leases
        state: absent
      become: true

    - name: Creating workspace
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - "{{ workspace_directory.base_path }}/{{ workspace_directory.config_dir }}"
        - "~/.ssh"

    - name: Creating ssh keys if not exists
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        

    - name: Creating tftpboot and nginx workspace
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - "{{ downloads.tftp_boot_root }}/{{ downloads.tftp_workspace_dir }}"
        - "{{ downloads.ngnix_document_root }}/{{ downloads.nginix_workspace_dir }}"
      become: True

    - name: Downloading installer and OCP cli
      unarchive:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
        validate_certs: no
      become: True
      loop:
        - "{{ downloads.utils.base_url + downloads.utils.ocp_oc_cli }}"
      when: not (skip_download | bool)

    - name: Downloading openshift-installer
      get_url:
        url: "{{ downloads.utils.base_url + downloads.utils.ocp_installer }}"
        dest: /tmp/installer.tar.gz

    - name: Unpacking installer
      unarchive:
        src: /tmp/installer.tar.gz
        dest: /usr/local/bin
        remote_src: yes
      become: true

    - name: Checking for openshift-install tool
      command: openshift-install
      register: output
      failed_when: output.rc !=0

    - name: Checking for OCP cli tool
      command: oc
      register: output
      failed_when: output.rc !=0

    - block:
       
        - name: Download initramfs and kernel 
          get_url:
            url: "{{ downloads.boot.base_url + item }}"
            dest: "{{ downloads.tftp_boot_root }}/{{ downloads.tftp_workspace_dir }}/{{ item }}"
          loop:
            - "{{ downloads.boot.initramfs }}"
            - "{{ downloads.boot.kernel }}"
          retries: 10
      

        - name: Download Red Hat CoreOS for bare metal
          get_url:
            url:  "{{ downloads.boot.base_url + downloads.boot.coreos }}"
            dest: "{{ downloads.ngnix_document_root }}/{{ downloads.nginix_workspace_dir }}/{{ downloads.boot.coreos }}"
          retries: 10
      when: not (skip_download | bool)
      become: true
        
          
          


