---

- name: Ovirt provisioning
  hosts: ovirt_engine
  become: True
  remote_user: vuberti
  gather_facts: false

  vars:
    engine_fqdn: ovengine.righini.local
    engine_user: vuberti@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    engine_password: vivaOpenshift

  tasks:
   - name: Obtain SSO token with using username/password credentials
     ovirt_auth:
       url: https://{{ engine_fqdn }}/ovirt-engine/api
       username: "{{ engine_user }}"
       ca_file: "{{ engine_cafile }}"
       password: "{{ engine_password }}"