---
- name: Install config
  hosts: bastion 
 
  tasks:
    
    - name: Removing config directory
      file:
        path: "{{ workspace_directory.base_path }}/{{ workspace_directory.config_dir }}"
        state: absent
      become: true

    - name: Creating config directory
      file:
        path: "{{ workspace_directory.base_path }}/{{ workspace_directory.config_dir }}"
        state: directory

    - name: Getting ssh public key
      slurp:
        src: ~/.ssh/id_rsa.pub
      register: key

    - set_fact:
        sshKey: "{{ key['content'] | b64decode }}"

    - name: Firing up install-config.yaml
      template:
        src: ../templates/install-config.j2
        dest: "{{ workspace_directory.base_path }}/{{ workspace_directory.config_dir }}/install-config.yaml"
      
  


            

        
        
