
---
- name: Install config
  hosts: bastion 
 
  tasks:


    - name: Creating csr approver script
      template:
        src: ../templates/csr.j2
        dest: "{{ workspace_directory.base_path }}/csr.sh"
        mode: '0755'

    - name: Installing csr cronjob
      cron:
        name: "Openshift csr approver"
        minute: "*/1"
        job: "{{ workspace_directory.base_path }}/csr.sh >> /tmp/aJob.log 2>&1"
        state: present
        user: "root"
      become: true
    
   
   